r update Update to meteor 1.2 => 1.3 => 1.4.1
Terminal error booting up Meteor:
I20160822-12:09:20.168(-5)? [Error: Can't find npm module 'react/package.json'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?]
I20160822-12:09:22.441(-5)? [Error: Can't find npm module 'react-dom/package.json'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?]
I20160822-12:09:22.442(-5)? [Error: Can't find npm module 'react-addons-transition-group/package.json'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?]
I20160822-12:09:22.442(-5)? [Error: Can't find npm module 'react-addons-css-transition-group/package.json'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?]
I20160822-12:09:22.443(-5)? [Error: Can't find npm module 'react-addons-linked-state-mixin/package.json'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?]
I20160822-12:09:22.443(-5)? [Error: Can't find npm module 'react-addons-create-fragment/package.json'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?]
I20160822-12:09:22.443(-5)? [Error: Can't find npm module 'react-addons-update/package.json'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?]
I20160822-12:09:22.444(-5)? [Error: Can't find npm module 'react-addons-pure-render-mixin/package.json'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?]
I20160822-12:09:22.444(-5)? [Error: Can't find npm module 'react-addons-test-utils/package.json'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?]
I20160822-12:09:22.444(-5)? [Error: Can't find npm module 'react-addons-perf/package.json'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?]
W20160822-12:09:22.449(-5)? (STDERR) WARNING: npm peer requirements not installed:
W20160822-12:09:22.449(-5)? (STDERR)  - react@0.14.x not installed.
W20160822-12:09:22.462(-5)? (STDERR)  - react-dom@0.14.x not installed.
W20160822-12:09:22.462(-5)? (STDERR)  - react-addons-transition-group@0.14.x not installed.
W20160822-12:09:22.462(-5)? (STDERR)  - react-addons-css-transition-group@0.14.x not installed.
W20160822-12:09:22.463(-5)? (STDERR)  - react-addons-linked-state-mixin@0.14.x not installed.
W20160822-12:09:22.463(-5)? (STDERR)  - react-addons-create-fragment@0.14.x not installed.
W20160822-12:09:22.463(-5)? (STDERR)  - react-addons-update@0.14.x not installed.
W20160822-12:09:22.463(-5)? (STDERR)  - react-addons-pure-render-mixin@0.14.x not installed.
W20160822-12:09:22.464(-5)? (STDERR)  - react-addons-test-utils@0.14.x not installed.
W20160822-12:09:22.464(-5)? (STDERR)  - react-addons-perf@0.14.x not installed.

Solution:

meteor npm install --save react react-dom react-addons-transition-group
react-addons-css-transition-group react-addons-linked-state-mixin react-addons-create-fragment react-addons-update react-addons-pure-render-mixin react-addons-test-utils react-addons-perf

react-addons-css-transition-group react-addons-linked-state-mixin react-addons-create-fragment react-addons-update react-addons-pure-render-mixin react-addons-test-utils react-addons-perf

meteor update --all-packages

1) Console ERROR: init.jsx:2 Uncaught TypeError: React.render is not a function
&
warning.js:36Warning: render(): Rendering components directly into document.body is discouraged, since its children are often manipulated by third-party scripts and browser extensions. This may lead to subtle reconciliation issues. Try rendering into a container element created for your app.

Solution:
	change
		React.render(<App />,  document.body);

	to
		ReactDOM.render(<App />,  document.getElementById('render-target'));

& in index.html:
	between:
		<body></body>
	add:
		<div id="render-target"></div>

2) Console Error: barchart.jsx:75 Uncaught TypeError: this.getDOMNode is not a function

Solution:
	change
		var el = this.getDOMNode(); // This is de div we are rendering
	to
		var el = ReactDOM.findDOMNode(this); // This is de div we are rendering

3) Console ERROR when submitting input of beers & date: beerform.jsx:4 Uncaught TypeError: React.findDOMNode is not a function

Solution:

beerform.jsx
line4
	Change:
		var numBeers = React.findDOMNode(this.refs.numBeers);
		var beerDate = React.findDOMNode(this.refs.beerDate);
	to:
		var numBeers = ReactDOM.findDOMNode(this.refs.numBeers);
		var beerDate = ReactDOM.findDOMNode(this.refs.beerDate);

Unsolved:
Still have this warning:
warning.js:36Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `BeerList`. See https://fb.me/react-warning-keys for more information.